openapi: 3.0.0
info:
  title: 文章翻訳API
  description: このAPIは、与えられた文章を翻訳する機能を提供します。現在、多くの言語に対応しています。
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /translate:
    post:
      summary: 文章を翻訳する
      description: 与えられた文章を指定された言語に翻訳します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: 翻訳する文章
                source_language:
                  type: string
                  description: 原文の言語コード（例：ja, en, zh）
                target_language:
                  type: string
                  description: 翻訳先の言語コード（例：ja, en, zh）
              required:
                - text
                - source_language
                - target_language
      responses:
        '200':
          description: 成功時のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  translated_text:
                    type: string
                    description: 翻訳された文章
        '400':
          description: リクエストに問題がある場合のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: エラーメッセージ
        '500':
          description: サーバーエラーが発生した場合のレスポンス
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: エラーメッセージ
